import { createSlice } from "@reduxjs/toolkit";

const initialState = [
    {
        hotelName: 'Light bright airy stylish apt & safe peaceful stay',
        hotelFeature: [
            'Wif Air conditioning Kitchen',
            'Cancellation flexibility available',
        ],
        location: "Cox's Bazar",
        image: 'https://i.ibb.co/6Pdmsfj/coxs-bazar1.jpg',
        bedrooms: 2,
        beds: 2,
        baths: 2,
        rating: 4.9,
        price: 34,
    },
    {
        hotelName: 'Apartment in Lost Panorama',
        hotelFeature: [
            'Wif Air conditioning Kitchen',
            'Cancellation flexibility available',
        ],
        location: "Cox's Bazar",
        image: 'https://i.ibb.co/pvz2NC5/New-Project.jpg',
        bedrooms: 2,
        beds: 2,
        baths: 2,
        rating: 4.9,
        price: 52,
    },
    {
        hotelName: 'AR Lounge & Pool (r&r + b&b)',
        hotelFeature: [
            'Wif Air conditioning Kitchen',
            'Cancellation flexibility available',
        ],
        location: "Cox's Bazar",
        image: 'https://i.ibb.co/dGdn6Bj/coxs-bazar-2.png',
        bedrooms: 2,
        beds: 2,
        baths: 2,
        rating: 4.9,
        price: 44,
    },
    {
        hotelName: 'Light bright airy stylish apt & safe peaceful stay',
        hotelFeature: [
            'Wif Air conditioning Kitchen',
            'Cancellation flexibility available',
        ],
        location: 'Sundarban',
        image: 'https://i.ibb.co/jwD7FyH/sundarban-3.jpg',
        bedrooms: 2,
        beds: 2,
        baths: 2,
        rating: 4.9,
        price: 37,
    },
    {
        hotelName: 'Apartment in Lost Panorama',
        hotelFeature: [
            'Wif Air conditioning Kitchen',
            'Cancellation flexibility available',
        ],
        location: 'Sundarban',
        image: 'https://i.ibb.co/Y34NMbr/sundarban-2.jpg',
        bedrooms: 2,
        beds: 2,
        baths: 2,
        rating: 4.9,
        price: 43,
    },
    {
        hotelName: 'AR Lounge & Pool (r&r + b&b)',
        hotelFeature: [
            'Wif Air conditioning Kitchen',
            'Cancellation flexibility available',
        ],
        location: 'Sundarban',
        image: 'https://i.ibb.co/KzcGBWm/bandarban-3.jpg',
        bedrooms: 2,
        beds: 2,
        baths: 2,
        rating: 4.9,
        price: 39,
    },
    {
        hotelName: 'Apartment in Lost Panorama',
        hotelFeature: [
            'Wif Air conditioning Kitchen',
            'Cancellation flexibility available',
        ],
        location: 'Bandarban',
        image: 'https://i.ibb.co/y0p81vd/bandarban-1.jpg',
        bedrooms: 2,
        beds: 2,
        baths: 2,
        rating: 4.9,
        price: 43,
    },
    {
        hotelName: 'Light bright airy stylish apt & safe peaceful stay',
        hotelFeature: [
            'Wif Air conditioning Kitchen',
            'Cancellation flexibility available',
        ],
        location: 'Bandarban',
        image: 'https://i.ibb.co/KzcGBWm/bandarban-3.jpg',
        bedrooms: 2,
        beds: 2,
        baths: 2,
        rating: 4.9,
        price: 48,
    },
    {
        hotelName: 'AR Lounge & Pool (r&r + b&b)',
        hotelFeature: [
            'Wif Air conditioning Kitchen',
            'Cancellation flexibility available',
        ],
        location: 'Bandarban',
        image: 'https://i.ibb.co/0mjy8nG/bandarban-2.jpg',
        bedrooms: 2,
        beds: 2,
        baths: 2,
        rating: 4.9,
        price: 44,
    },
    {
        hotelName: 'Apartment in Lost Panorama',
        hotelFeature: [
            'Wif Air conditioning Kitchen',
            'Cancellation flexibility available',
        ],
        location: 'Sajek Valley',
        image: 'https://i.ibb.co/wpLdH2m/sajek-3.jpg',
        bedrooms: 2,
        beds: 2,
        baths: 2,
        rating: 4.9,
        price: 43,
    },
    {
        hotelName: 'Light bright airy stylish apt & safe peaceful stay',
        hotelFeature: [
            'Wif Air conditioning Kitchen',
            'Cancellation flexibility available',
        ],
        location: 'Sajek Valley',
        image: 'https://i.ibb.co/Y0x771w/sajek-1.jpg',
        bedrooms: 2,
        beds: 2,
        baths: 2,
        rating: 4.9,
        price: 48,
    },
    {
        hotelName: 'AR Lounge & Pool (r&r + b&b)',
        hotelFeature: [
            'Wif Air conditioning Kitchen',
            'Cancellation flexibility available',
        ],
        location: 'Sajek Valley',
        image: 'https://i.ibb.co/Nr01nHH/sajek-2.jpg',
        bedrooms: 2,
        beds: 2,
        baths: 2,
        rating: 4.9,
        price: 44,
    },
];

const hotelSlice = createSlice({
    name: 'hotel',
    initialState,
})

export default hotelSlice.reducer;